#! /bin/bash

# Set variables
THISDIR="$( cd $(dirname $0); pwd)"
SCRIPT="$THISDIR/$(basename $0)"
export GROUPER_HOME=/opt/internet2/grouper/grouper.apiBinary
GSH_JYTHON="$GROUPER_HOME/bin/gsh.jython"

# Run script via `gsh.jython`
("$GSH_JYTHON" "$THISDIR/list_export_groups.py" "$@" 3>&2 2>&1 1>&3) 2>/dev/null
#("$GSH_JYTHON" "$THISDIR/list_export_groups.py" "$@" 3>&2 2>&1 1>&3) 2>/dev/null

